services:
  - type: web
    name: plant-health-maize-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
